testrg:
  name: "myResourceGroup123"

networks:
  network1:
    address_space:
     - "10.0.1.0/16"
    dns_servers:
     - "10.0.1.4"
     - "10.0.1.5"
  
  network2:
    address_space:
     - "10.0.2.0/16"
    dns_servers:
     - "10.0.2.4"
     - "10.0.2.5"
