testrg:
  name: "myResourceGroup123"

networks:
  network1:
    address_space:
     - "10.1.0.0/16"
    dns_servers:
     - "10.1.0.4"
     - "10.1.0.5"
  
  network2:
    address_space:
     - "10.2.0.0/16"
    dns_servers:
     - "10.2.0.4"
     - "10.2.0.5"
