testrg:
  name: "myResourceGroup123"

networks:
  network1:
    address_space:
     - "10.1.0.0/16"
    dns_servers:
     - "4.2.2.2"
     - "8.8.8.8"
    subnets:
      subnet1:
        address_prefix: "10.1.1.0/24"
#        security_group_id: ""
      subnet2:
        address_prefix: "10.1.2.0/24"
#        security_group_id: ""
  
  network2:
    address_space:
     - "10.2.0.0/16"
    dns_servers:
     - "4.2.2.2"
     - "8.8.8.8"
    subnets:
      subnet1:
        address_prefix: "10.2.1.0/24"
#        security_group_id: ""
      subnet2:
        address_prefix: "10.2.2.0/24"
#        security_group_id: ""

security_groups:
